string = input("Enter a string: ")
print("Uppercase:", string.upper())
print("Lowercase:", string.lower())
print("Split:", string.split())
print("Count of 'a':", string.count('a'))
print("Replace 'a' with 'e':", string.replace('a', 'e'))
print("Find 'test':", string.find('test'))
print("Krishna Bhatia 1/23/SET/BCS/358")
